spring.application.name=ControleAcesso

# Conexao com o MySQL
# Repare que depois do igual em password nao tem NADA (nem espaco)
spring.datasource.url=jdbc:mysql://localhost:3306/controle_acesso?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=barakar!10278!

# Configuracoes do Hibernate (Isso vai criar as tabelas 'alunos' sozinho para voce)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect